version: '3.8'
services:
  retail:
    image: postgres:latest
    container_name: retail-database
    environment:
      POSTGRES_USER: toteall
      POSTGRES_PASSWORD: toteall
      POSTGRES_DB: retail
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
