apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the size based on your needs
